//! QMD - Query Markup Documents (Rust port)
//!
//! Secure, fast, on-device hybrid search for markdown and knowledge bases.
//! Drop-in replacement for the Node.js original with better security profile.
//!
//! # For Rust newbies (Python / Node.js / TypeScript background)
//!
//! This file is the equivalent of:
//! - `src/cli/qmd.ts` (the main CLI entry point) in the original project, **plus**
//! - the "bin" launcher logic.
//!
//! Key Rust concepts explained inline with comments:
//! - `struct` + `enum` with `#[derive(Parser)]` from the `clap` crate
//!   replaces `argparse.ArgumentParser` (Python) or `yargs`/`commander` (Node).
//!   The derive macro generates all the parsing + `--help` for free.
//! - `Option<T>` is Rust's version of `T | null` / `Optional[T]` / `T | undefined`.
//! - `Result<T, E>` + the `?` operator is how Rust does error handling without
//!   exceptions. Think of it as "explicit try/catch that the compiler enforces".
//!   We use `anyhow::Result` because it is the most ergonomic choice for CLI tools
//!   (it can hold any error and still gives nice `.context()` messages).
//! - `&str` vs `String`: `&str` is a cheap borrowed view (like a slice), `String`
//!   owns heap-allocated data. Pass `&str` to functions when you don't need ownership.
//! - Pattern matching (`match`, `if let Some(x)`) is one of Rust's superpowers.
//!   It is exhaustive and prevents the "forgot a case" bugs common in other languages.
//!
//! Core command logic has been extracted to `src/cli/commands/*.rs` (status, collection,
//! ls, get, search, mcp). Continue the pattern for remaining commands. See AGENTS.md
//! and the implementation summary for the contributor workflow.

use anyhow::Result;
use clap::Parser;

const VERSION: &str = env!("CARGO_PKG_VERSION");

// Use the extracted CLI argument types from the library.
// Commands and action types are re-exported / available via the qmd crate.
use qmd::cli::args::{Cli, Commands};

/// The program entry point (like `if __name__ == "__main__":` in Python or
/// the body of `bin/qmd` + the default export in the original TS CLI).
///
/// `main` must return `Result<(), anyhow::Error>` (or `()`) so we can use the `?`
/// operator for clean error propagation. If any function using `?` fails, the
/// error bubbles up and `anyhow` prints a nice message + backtrace (if RUST_BACKTRACE=1).
///
/// `Cli::parse()` is generated by clap at compile time. It reads `std::env::args()`
/// (the equivalent of `process.argv` in Node or `sys.argv` in Python) and turns
/// it into the strongly-typed `Cli` struct we defined above.
fn main() -> Result<()> {
    let cli = Cli::parse();

    // Rust's `match` is exhaustive and extremely powerful.
    // It is the primary way we "dispatch" on which subcommand the user asked for.
    // Because `Commands` is an enum, the compiler guarantees we handle every possible case.
    match cli.command {
        None => {
            // No subcommand — print friendly help
            println!("qmd (Rust port) v{} — use --help for usage", VERSION);
            println!(
                "Primary: qmd query <q> | search <q> | vsearch <q> | get <file> | status | mcp"
            );
            println!("(Node reference binary available for comparison if installed.)");
        }

        Some(Commands::Status { json }) => {
            qmd::cli::commands::status::cmd_status(json)?;
        }

        Some(Commands::Init { force }) => {
            qmd::cli::commands::init::cmd_init(force)?;
        }

        Some(Commands::Collection { action }) => {
            qmd::cli::commands::collection::cmd_collection(action)?;
        }

        Some(Commands::Ls { path }) => {
            qmd::cli::commands::ls::cmd_ls(path)?;
        }

        Some(Commands::Get {
            file,
            l,
            full,
            line_numbers,
        }) => {
            qmd::cli::commands::get::cmd_get(file, l, full, line_numbers)?;
        }

        Some(Commands::MultiGet {
            pattern,
            l,
            max_bytes,
            format,
        }) => {
            qmd::cli::commands::multi_get::cmd_multi_get(pattern, l, max_bytes, format)?;
        }

        Some(Commands::Search {
            query,
            n,
            all,
            min_score,
            format,
            collection,
            json,
            files,
        }) => {
            qmd::cli::commands::search::cmd_search(
                query, n, all, min_score, format, collection, json, files,
            )?;
        }

        Some(Commands::Query {
            query,
            n,
            all,
            min_score,
            format,
            collection,
            explain,
            no_rerank,
            candidate_limit,
            full,
            line_numbers,
        }) => {
            qmd::cli::commands::query::cmd_query(
                query,
                n,
                all,
                min_score,
                format,
                collection,
                explain,
                no_rerank,
                candidate_limit,
                full,
                line_numbers,
            )?;
        }

        Some(Commands::Vsearch {
            query,
            n,
            all,
            min_score,
            format,
            collection,
            full,
            line_numbers,
        }) => {
            qmd::cli::commands::query::cmd_vsearch(
                query,
                n,
                all,
                min_score,
                format,
                collection,
                full,
                line_numbers,
            )?;
        }

        Some(Commands::Mcp { http, port, daemon }) => {
            qmd::cli::commands::mcp::cmd_mcp(http, port, daemon)?;
        }

        Some(Commands::Update {
            pull,
            embed,
            chunk_strategy,
        }) => {
            qmd::cli::commands::update::cmd_update(pull, embed, chunk_strategy)?;
        }

        Some(Commands::Embed {
            force,
            collection,
            chunk_strategy,
        }) => {
            qmd::cli::commands::embed::cmd_embed(force, collection, chunk_strategy)?;
        }

        Some(Commands::Context { action }) => {
            qmd::cli::commands::context::cmd_context(action)?;
        }

        Some(Commands::Cleanup) => {
            qmd::cli::commands::cleanup::cmd_cleanup()?;
        }

        // All Commands variants declared in cli/args.rs now have dedicated dispatch arms
        // (I1 surface completeness + I2/I3 features fully wired). No catch-all remains.
        Some(Commands::Bench { fixture }) => {
            qmd::cli::commands::bench::cmd_bench(fixture)?;
        }

        Some(Commands::Skills { action }) => {
            qmd::cli::commands::skill::cmd_skills(action)?;
        }

        Some(Commands::Skill { action }) => {
            qmd::cli::commands::skill::cmd_skill(action)?;
        }
    }

    // Finalize any exit code staged via the atomic helpers (QmdError trait
    // foundation prepared for later slices). This is the small main.rs
    // integration point. For Rust newbies: after the big match, we check the
    // Atomic global and exit early if a command path wanted a non-standard
    // status (e.g. 2 for usage-like "not implemented yet"). Only atomics are
    // exercised in this slice per the one-site rule.
    let code = qmd::utils::finalize_exit_code();
    if code != 0 {
        std::process::exit(code);
    }

    Ok(())
}

// Command implementations have been fully extracted to src/cli/commands/*
// (collection.rs, ls.rs, get.rs, search.rs, mcp.rs, status.rs, query.rs) following the target modular layout.
// Helpers (parse_qmd_virtual, escape_like, get_body_from_db, parse_structured_query) live in commands/mod.rs for sharing.
// main.rs is now a thin entrypoint: parse + dispatch only.
